user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /dev/stderr warn;
events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  access_log /dev/stdout;
  sendfile on;
  server_tokens off;
  server {
    listen 8080;
    root /var/www/html/public;
    index index.php;
    client_max_body_size 32m;
    location = /__cloud_health {
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME /var/www/html/public/__cloud_health.php;
      fastcgi_pass 127.0.0.1:9000;
    }
    location / { try_files $uri $uri/ /index.php?$query_string; }
    location = /index.php {
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
      fastcgi_param HTTPS on;
      fastcgi_param SERVER_PORT 443;
      fastcgi_param HTTP_X_FORWARDED_PROTO https;
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_read_timeout 60s;
    }
    location ~ \.php$ { return 404; }
    location ~ /\. { deny all; }
  }
}
