[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/run/supervisord.pid
[program:octane]
command=php artisan octane:start --server=roadrunner --host=127.0.0.1 --port=8000 --rpc-host=127.0.0.1 --rpc-port=6001 --workers=2 --max-requests=500 --rr-config=/etc/spartan/rr.yaml --no-interaction
directory=/var/www/html
user=www-data
stopasgroup=true
killasgroup=true
stopwaitsecs=70
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
[program:queue]
stopasgroup=true
killasgroup=true
stopwaitsecs=120
command=/bin/sh -c 'if [ "$CLOUD_ROLE" = primary ]; then exec php artisan queue:work --queue=critical,high,medium,default,low --sleep=3 --tries=3 --timeout=50 --max-time=3600; else exec sleep infinity; fi'
directory=/var/www/html
user=www-data
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
[program:scheduler]
stopasgroup=true
killasgroup=true
stopwaitsecs=70
command=/bin/sh -c 'if [ "$CLOUD_ROLE" = primary ]; then exec php artisan schedule:work; else exec sleep infinity; fi'
directory=/var/www/html
user=www-data
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
[program:redis]
command=redis-server /etc/spartan/redis.conf
user=www-data
priority=1
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
