compatibility_date = "2026-10-01"
name = "dezerx-spartant-cloud"
main = "routing.js"
workers_dev = true

[observability]
enabled = true

[vars]
MAX_CUSTOM_HOSTNAMES = "30"
BASE_DOMAIN = "load.dezerx.cloud"
US_ORIGIN = "https://node-us.dezerx.cloud"
DE_ORIGIN = "https://node-de.dezerx.cloud"
CLOUDFLARE_ZONE_ID = "9709025acf2bfa1c3d8a513c923a5f94"
SAAS_ZONE_DOMAIN = "dezerx.cloud"
SAAS_CNAME_TARGET = "load.dezerx.cloud"


[[migrations]]
tag = "routing-v1"
new_sqlite_classes = ["RoutingTenant", "Domains"]

[[migrations]]
tag = "routing-v2-d1-only"
deleted_classes = ["RoutingTenant", "Domains"]

[triggers]
crons = ["*/5 * * * *"]

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = true


[[routes]]
pattern = "load.dezerx.cloud/*"
zone_id = "9709025acf2bfa1c3d8a513c923a5f94"

[[routes]]
pattern = "*.load.dezerx.cloud/*"
zone_id = "9709025acf2bfa1c3d8a513c923a5f94"

[[d1_databases]]
binding = "DB"
database_name = "spartan-routing-load-dezerx-cloud"
database_id = "2551e490-663e-4fb7-b7b5-0fe468eca54a"
migrations_dir = "migrations"
